### ISSUE TITLE
Not an Issue : Is there a reference to create a sample AFP file with Images( IOCA images, not Object container)

### ISSUE THREAD

**Issue by harimurra** [yan74/afplib#12]

**Comment by yan74** [comment]
no there is not and this will take some time to create - any particular image format you are looking for?

**Comment by harimurra** [comment]
Am looking for Jpg format Yan, 
Thank you.

**Comment by yan74** [comment]
well PSEG (aka page segment) is not an image format. I was asking if you want to include e.g. JPEG or IBM MMR encoded images. Please have a look at the IOCA manual which formats are possible.

**Comment by harimurra** [comment]
Thanks Yan, 
i will take a look into that.

**Comment by harimurra** [comment]
[https://github.com/yan74/afplib/issues/20](#20)
