### ISSUE TITLE
CMYK Object creation - Not an Issue

### ISSUE THREAD

**Issue by bintesh** [yan74/afplib#14]
Hi Yan, 
Can you guide me in creating CMYK object? 
I did try the below, But its not working. 
`.withMember(new AfpBuilder()
.with(AfplibPackage.SEC__COLSIZE1, 0)
.with(AfplibPackage.SEC__COLSIZE1, 0)
.with(AfplibPackage.SEC__COLSIZE1, 0)
.with(AfplibPackage.SEC__COLSIZE1, 255)
.create(SEC.class))`

I am trying to simulate a working AFP and it looks like the below when open in AFP explorer.
SEC CMYK=0,0,0,255

**Comment by yan74** [comment]
@bintesh,

try this instead:

    new AfpBuilder() 
        .with(AfplibPackage.SEC__COLSIZE1, 0x000000ff)
        .create(SEC.class);

**Comment by yan74** [comment]
@bintesh,

can you confirm this is what you expected?

**Comment by bintesh** [comment]
Hi Yan,
Unfortunately not working.. still not creating CMYK object.

**Comment by yan74** [comment]
@bintesh,

ok then I need a little more context here - what do you want to achieve. Do you have any sample files?

y

**Comment by bintesh** [comment]
I am trying to recreate a page which has a specific color ( kind of pink/ash... .) In source AFP the color is specified by CMYK  (CMYK 0,0,0,13). The only way to exactly match the color I believe is to have the exact same value for the CMYK object.  
see the screenshot below, hope this helps.
![secmnyk](https://cloud.githubusercontent.com/assets/28321298/26591668/fd484f32-4523-11e7-9d17-ebbd92cacbc0.JPG)

**Comment by yan74** [comment]
Have a look at this snippet:

https://raw.githubusercontent.com/yan74/afplib/cf5cfe6589bf6409f1c6925f4c9821bb1f81462b/org.afplib.samples/src/main/java/org/afplib/samples/snippets/CreatePage.java

		PTX ptx = new AfpBuilder()
				.withMember(new AfpBuilder()								// Text Orientation -> Left to Right // Top to Bottom
						.with(AfplibPackage.STO__IORNTION, STOIORNTION.CONST0DEGREES_VALUE)
						.with(AfplibPackage.STO__BORNTION, STOBORNTION.CONST90DEGREES_VALUE)
						.create(STO.class))
				.withMember(new AfpBuilder()
						.with(AfplibPackage.AMB__DSPLCMNT, 1440)			// Text Cursor to 1 inch from top edge of the paper
						.create(AMB.class))
				.withMember(new AfpBuilder()
						.with(AfplibPackage.AMI__DSPLCMNT, 720)				// Text Cursor to 0.5 inches from left edge of the paper
						.create(AMI.class))
				.withMember(new AfpBuilder()								// Text Color
						.with(AfplibPackage.SEC__COLSPCE, SECCOLSPCE.CONST_CMYK_VALUE)
						.with(AfplibPackage.SEC__COLSIZE1, 8)
						.with(AfplibPackage.SEC__COLSIZE2, 8)
						.with(AfplibPackage.SEC__COLSIZE3, 8)
						.with(AfplibPackage.SEC__COLSIZE4, 8)
						.with(AfplibPackage.SEC__COLVALUE, new byte[] { (byte) 0x90, (byte) 0xB2, 0x00, 0x00} )
						.create(SEC.class))
				.withMember(new AfpBuilder()
						.with(AfplibPackage.SCFL__LID, 1)					// identifier mapped in MCF above
						.create(SCFL.class))
				.withMember(new AfpBuilder()
						.with(AfplibPackage.TRN__TRNDATA, text)
						.create(TRN.class))
				.create(PTX.class);

The code above is responsible for placing the text (Hello World) in pink. The complete snippet does create a full page including font mapping. This is how it looks like:

![purpletext](https://cloud.githubusercontent.com/assets/7473685/26595294/3614deb0-456b-11e7-9a79-293c3ca937ce.png)

Hope that helps!

**Comment by bintesh** [comment]
Thanks Yan. It worked!!!
