### ISSUE TITLE
Not an Issue : Looking for a snippet

### ISSUE THREAD

**Issue by harimurra** [yan74/afplib#15]
Hi yan,
Is there a reference to create  Section box like below Image. 
![section](https://cloud.githubusercontent.com/assets/28309437/26602328/be5c344e-4548-11e7-9567-d350bb663336.jpg)

**Comment by yan74** [comment]
@harimurra not sure what you are asking for? A sample how to include this image?

**Comment by harimurra** [comment]
Hi yan,

not an  Image, am looking for How to Create a Rectangular Box to Contain Text.

**Comment by yan74** [comment]
Well you may want to look at

https://raw.githubusercontent.com/yan74/afplib/cf5cfe6589bf6409f1c6925f4c9821bb1f81462b/org.afplib.samples/src/main/java/org/afplib/samples/snippets/CreatePage.java

This puts "Hello World" on a page - in AFP text flows according to writing direction (aka inline direction) and font spacing. You can't define a box that aligns the text within. You would have to calculate dimensions of the text yourself and align accordingly by breaking the text into separate TRNs.

**Comment by harimurra** [comment]
`out.writeStructuredField(new AfpBuilder()
				.withMember(new AfpBuilder()								//  Color
						.with(AfplibPackage.SEC__COLSPCE, SECCOLSPCE.CONST_CMYK_VALUE)
						.with(AfplibPackage.SEC__COLSIZE1, 0)
						.with(AfplibPackage.SEC__COLSIZE2, 0)
						.with(AfplibPackage.SEC__COLSIZE3, 0)
						.with(AfplibPackage.SEC__COLSIZE4, 31)
						.with(AfplibPackage.SEC__COLVALUE, new byte[] { (byte) 0x00, (byte) 0x00,  0x00,0x1F} )
						.create(SEC.class))
				.withMember(new AfpBuilder()
						.with(AfplibPackage.AMI__DSPLCMNT, 1400)				
						.create(AMI.class))
				.withMember(new AfpBuilder()
						.with(AfplibPackage.AMB__DSPLCMNT, 130)			
						.create(AMB.class))
				.withMember(new AfpBuilder()
						.with(AfplibPackage.DBR__RLENGTH, 550)  // Section Box
						.with(AfplibPackage.DBR__RWIDTH, 850)
						.create(DBR.class))
				.create(PTX.class));`
