### ISSUE TITLE
Not an Issue : How to set location of elements(Image,text etc.) on a page?

### ISSUE THREAD

**Issue by saurabhsonkar** [yan74/afplib#16]

**Comment by yan74** [comment]
Hi @saurabhsonkar,

this depends really on the object you are referencing. Easiest way would be to put your elements (Image, text) into an overlay. An overlay looks very similar to a page despite that it is not :) An overlay then is referenced from a page with an IOB and there you have your x and y offset.

**Comment by saurabhsonkar** [comment]
Hi Yan74,
I'm using elements like IOB, GDO, DIR etc. and placing elements on the exact position in the page.
Could you please provide a snippet to do so.
Thanks in advance.

**Comment by yan74** [comment]
@saurabhsonkar,

I found some code I've written some time ago that shifts contents on a page - here is a snippet of it:

                    if(sf instanceof IPO) {
                        ((IPO)sf).setXolOset(add_x + ((IPO)sf).getXolOset());
                    }

                    if(sf instanceof IOB) {
                        ((IOB)sf).setXoaOset(add_x + ((IOB)sf).getXoaOset());
                        writeSF(raf, sf);
                    }

                    if(sf instanceof IPS) {
                        ((IPS)sf).setXpsOset(add_x + ((IPS)sf).getXpsOset());
                    }

                    out.writeStructuredField(sf);

**Comment by preddy321** [comment]
working on it Yan, will update whats going on..............

**Comment by saurabhsonkar** [comment]
Thanks, Yan.
