### ISSUE TITLE
Not an Issue : TLE Object creation.

### ISSUE THREAD

**Issue by preddy321** [yan74/afplib#17]
Hi Yan,
Can you please guide me in creating TLE object with parameter Values like ItemName=LANGUAGE  ItemValue=E  PgName=  PgGroupName=.

**Comment by preddy321** [comment]
Hi Yan, 

am able to create now. 

Thanks.

**Comment by saurabhsonkar** [comment]
Hey @preddy321, Could you please provide the snippet of  TLE object with parameter Values like ItemName=LANGUAGE ItemValue=E PgName= PgGroupName=.
Thanks
