### ISSUE TITLE
Split AFP File

### ISSUE THREAD

**Issue by timyounes** [yan74/afplib#2]
Hi,
I just want to know if in this AFP library you already included the functions of splitting AFP file? Like for example splitting in pages single or multiple, or by name page group something like that or splitting it by TLE.

**Comment by yan74** [comment]
Hi timyounes,

afplib is a low level API to map structured fields, triplets, ... to JAVA objects. You can certainly implement higher functions like the split you are looking for - as I show in the samples section. You can find the opposite (merge multiple files into one) as an example there. But no - so far I haven't done a split yet. But should be rather straight forward. I'd be happy if you would contribute such a function :)

**Comment by timyounes** [comment]
Thanks @yan74. I'm not really good in java but  I will do my best to contribute that kind of function. :)

**Comment by yan74** [comment]
@timyounes if you need help with that ... just ask

**Comment by agwego** [comment]
Has this split functionality been implemented?

**Comment by timyounes** [comment]
Not yet.. If you want I have some source about splitting AFP file but not in java language

**Comment by agwego** [comment]
Java preferably but anything will do, I'd try and convert it to Java and contribute the code.

**Comment by timyounes** [comment]
Please check this link [https://github.com/audreyt/openafp-utils](url)

**Comment by Hemanth440** [comment]
Has this split functionality been implemented in Java?
