### ISSUE TITLE
Not an issue: How can we create a circle?

### ISSUE THREAD

**Issue by saurabhsonkar** [yan74/afplib#25]
Just like section box(SEC class) can we create a circle?

**Comment by yan74** [comment]
Hi @saurabhsonkar,

so SEC in PTOCA is Set Extended Color. I can think of several options to create a circle in AFP

1. include an image (IOCA or object container)
2. include a pdf that has a vector image in it (object container)
3. use a font like wingdings that has some circle shaped glyph
4. use an arc command in a GOCA drawing subset

Programming wise number 2 may be the easiest one. Depending on what you want to achieve number 4 may make the most sense but also is a lot of programming effort (lots of structured fields to create).

**Comment by saurabhsonkar** [comment]
Thank you, Yan for brief reply. I'm just curious about the last approach. Could you please provide me a snippet.

**Comment by yan74** [comment]
no I don't have a sample, sorry :) - closing as this is a year old
