### ISSUE TITLE
Font Description Specification

### ISSUE THREAD

**Issue by saasgasques** [yan74/afplib#26]
Hi Yan,

First thanks for publish such api and open de afp world to the mortals :-)

Reading the specification for "Font Description Specification"."FtDsFlags" I think that for a 'Proportionally spaced characters' the value has to be 5 that is 00000101.
`.with(AfplibPackage.FONT_DESCRIPTOR_SPECIFICATION__FT_DS_FLAGS, FontDescriptorSpecificationFtDsFlags.PROPORTIONALLYSPACED_VALUE | FontDescriptorSpecificationFtDsFlags.PARAMETERISSPECIFIED_VALUE)`

And this require to change PROPORTIONALLYSPACED_VALUE from 32 to 4 and PARAMETERISSPECIFIED_VALUE from 128 to 1 in the enumeration "FontDescriptorSpecificationFtDsFlags".

Is this correct or I'm wrong?

**Comment by yan74** [comment]
Well I think this is modeled wrong in afplib - I double checked and I think I was sort of braindead when implementing this - so 5 (or 4) is the right answer for having proportionally spaced font. What afplib wants to express is that PROPORTIONALLYSPACED_VALUE is bit number 5 in FtDsFlags. It does that by storing 2^5 (=32) in the enum value. It should have stored 2^(7-5) = 4 there. So I shall fix that and then your code above would be right.

**Comment by yan74** [comment]
so latest commit should have that changed ... see if it works for you now.

**Comment by saasgasques** [comment]
Thanks Yan,
