### ISSUE TITLE
Not an Issue Hi Yan,  Is there a reference to create a  TRN Obj with right align ?

### ISSUE THREAD

**Issue by harimurra** [yan74/afplib#32]
Hi Yan,

 Is there a reference to create a  TRN Obj with right align?

**Comment by yan74** [comment]
Although this is somewhat old - had overlooked this ... Positioning of text in AFP needs to be done by the composer. So you need to calculate the flow and positioning of your glyphs yourself. And no I haven't written any text layouting code ... this sounds to be a very tedious task ... :) Maybe Apache FOP is a better place to look for something like this.
