### ISSUE TITLE
Cannot read IOCA images  

### ISSUE THREAD

**Issue by AkashChikane** [yan74/afplib#37]
I am able to read IOCA file and get IPD objects how can i use IPD.getIOCAdat() data to create image?

`          	IPD xx=(IPD)sf; `          
 	        `bop=new ByteArrayOutputStream();`
            	`byte bxx[]=xx.getIOCAdat();`       	
            	`bop.write(bxx);`

IPD shows fileds shows it uses CMYK colors

**Comment by AkashChikane** [comment]
how to convert `getIOCAdat()` to image ?

**Comment by AkashChikane** [comment]
thank you @yan74  that helped a lot i referred to function set 45 and cmyk data fromat as well as Image Tiling used in afp processed it in .dat file and used python PIL to convert image data in png as you mention in [#38](https://github.com/yan74/afplib/issues/38) it is painful in java using JAI.

**Comment by guilllt** [comment]
Hi @AkashChikane by any chance do you have sample codes i can refer to in converting image data to png?  :) thanks!!

**Comment by AkashChikanep4** [comment]
Hi @guilllt No sorry this was way long back. But it was quite straight forward once i converted and imported data in PIL
