### ISSUE TITLE
How to convert PNG/JPG image to CMYK and separated the color planes and stored the data uncompressed in .dat files?

### ISSUE THREAD

**Issue by gurunathrokkam** [yan74/afplib#38]
Hi @yan74,

Can you help on "**convert the image to CMYK and separated the color planes and stored the data uncompressed in .dat files**"?  
I tried using ImageMagick, but couldn't.

Is it possible in Java by chance?

Thank you in advance.

_Originally posted by @gurunathrokkam in https://github.com/yan74/afplib/issues/20#issuecomment-434578260_

**Comment by yan74** [comment]
Hi @gurunathrokkam,

to separate the CMYK with image magick this should do the trick:
`convert <input> -colorspace CMYK -channel K -separate channel_black.dat`
(found here: http://www.imagemagick.org/Usage/color_basics/#separate)

Doing this in Java is painful as I wrote earlier :) - I once did the opposite (merging CMYK bands into a single RenderedImage) using the BandMerge JAI Operation. You may be able to achieve separation by using the BandSelect (https://docs.oracle.com/cd/E17802_01/products/products/java-media/jai/forDevelopers/jai-apidocs/javax/media/jai/operator/BandSelectDescriptor.html) however I have not tried this.

**Comment by gurunathrokkam** [comment]
Thanks @yan74
