### ISSUE TITLE
Not Really An Issue - Just A Question

### ISSUE THREAD

**Issue by TheClark** [yan74/afplib#41]
To create an IOCA image from the snippet, how does a person get the *.dat data from an existing TIF file?  I tried JAI but the raw raster looks way too big.  Curious how you did it. thanks!

**Comment by yan74** [comment]
So a couple of thoughts here:

1. see #20 
2. Using ImageMagick you can convert to CMYK (if not done already) and separate and uncompress the planes:
```
convert input.tif -colorspace CMYK -separate separate_CMYK_%d.dat
```
3. JAI should be able to do the same
4. uncompressed (printable) image data indeed is big
5. you may use e.g. LZW to compress the data before embedding (use the appropriate ImageEncodingCOMPRID flag to indicate which compression you used).
6. although it might be big the snippet should work (it will split the data in 30kB chunks)

**Comment by yan74** [comment]
#20

**Comment by TheClark** [comment]
Awesome, you rock!  Thanks for the reply, cannot wait to try it.

**Comment by TheClark** [comment]
I was able to separate the TIF using imagemagick, which was awesome.  However, I couldn't add these properly to the  AFP file, the output was garbled.  

I tried using ImageEncodingCOMPRID.CONST_TIFFLZW_VALUE and uncompressed with no luck.  Uncompressed was like color static, TIFFLZW was a solid color (black or white, I cannot remember).    

Feeling stuck!  Willing to trade beer or coffee for help ;-)

**Comment by yan74** [comment]
Ok I‘ll go for the beer then :) Let me see if I find some time over the weekend to look at this. In the meantime:

1. Did you get the snippet working successfully?
2. If so, I believe there is the source png somewhere in the repository that I used to create the separate planes using ImageMagick. If you use the command above on that source png is the outcome still working with the snippet? So that we verify the command actually does produce the right type of data.
3. I would try working with uncompressed data first. And then maybe try jpeg next as this is immediately useable in the IOCA. JPEG might be ok for pictures ...

**Comment by TheClark** [comment]
Beer it is!  But you will have to buy it, too expensive to ship!  LMK how i can say 'thanks' with paypal or patreon or something, much appreciated!.  

The snippet works perfect with your.dat files, just not mine.  I will hunt down that png and give it a shot.  

The input has to be CMYK tiffs for this project, but its a good idea to try other formats and taste a little success.

Thanks!

**Comment by TheClark** [comment]
> Ok I‘ll go for the beer then :) Let me see if I find some time over the weekend to look at this. In the meantime:
> 
> 1. Did you get the snippet working successfully?
> 2. If so, I believe there is the source png somewhere in the repository that I used to create the separate planes using ImageMagick. If you use the command above on that source png is the outcome still working with the snippet? So that we verify the command actually does produce the right type of data.
> 3. I would try working with uncompressed data first. And then maybe try jpeg next as this is immediately useable in the IOCA. JPEG might be ok for pictures ...

Good stuff!

I tried the png in the repository with the command above, it generates 4 .dat files, good!

However, the.dat files are far different than the ones in the repository.   The ones in the repo are very raw and uncompressed looking, the freshly generated ones are just PNG files one per separation.

So I am thinking I need to tell IM to generate something else.  I ran identify -list and got a huge list of formats, and even tried a few like CMYK, but no dice.

**Comment by yan74** [comment]
Looks like the convert command was wrong ... my apologies for that. This should work:
```
convert img_800x480_3x8bit_RGB_color_bars_CMYKWRGB.png -colorspace cmyk -separate img_800x480_3x8bit_RGB_color_bars_CMYKWRGB_%d.gray
```
As for the compression this ought to work as well:
```
convert img_800x480_3x8bit_RGB_color_bars_CMYKWRGB.png -colorspace cmyk -separate img_800x480_3x8bit_RGB_color_bars_CMYKWRGB_%d.jpeg
```
If you want to go for lzw you'd need some additional processing as IOCA does not expect the tiff header to be present which you would get when exporting tiff using imagemagick. To remove the header should be doable though as tiff is well documented.

Regarding the beer - I'll collect the debt when I am in Portland :)
