### ISSUE TITLE
how to remove bdt edt tags

### ISSUE THREAD

**Issue by YogeshSharma1985** [yan74/afplib#45]
is there a method to use to remove extra bdt edt tags?
I only want to keep first and last tags

**Comment by yan74** [comment]
Hi @YogeshSharma1985,

I would use an AfpFilter like this:

```java
package org.afplib.samples;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

import org.afplib.afplib.SFName;
import org.afplib.base.SF;
import org.afplib.io.AfpFilter;
import org.afplib.io.AfpInputStream;
import org.afplib.io.AfpOutputStream;
import org.afplib.io.Filter;

public class RemoveBDTEDT {

	public static void main(String[] args) {
		try (AfpInputStream in = new AfpInputStream(
				new BufferedInputStream(new FileInputStream(args[0])));
				AfpOutputStream out = new AfpOutputStream(
						new BufferedOutputStream(new FileOutputStream(args[1])))) {

			AfpFilter.filter(in, out, new Filter() {
				
				int bdtNumber = 0;
				
				@Override
				public STATE onStructuredField(SF sf) {
					switch(sf.getId()) {

					case SFName.BDT_VALUE:
						bdtNumber++;
						if(bdtNumber > 1) {
							return STATE.DROP;
						}
						return STATE.UNTOUCHED;

					case SFName.EDT_VALUE:
						if(bdtNumber > 1) {
							return STATE.DROP;
						}
						bdtNumber--;
						return STATE.UNTOUCHED;

					}
					return STATE.UNTOUCHED;
				}
			}); 
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```

However there may be side effects if the BDT has an environment group. If not, this should work (haven't tested it though).

**Comment by YogeshSharma1985** [comment]
thanks, much appreciated.

**Comment by YogeshSharma1985** [comment]
Yan,

      I have couple of more questions and I apologize in advance for not being well versed in Java.

     How can I move (up or down)/delete some tags like NOPs, BNG/ENGs?

    I also need to delete certain BNG/ENG based on the location of their occurrence (if the field just before the BNG is a certain NOP)

   Is it possible to use AFPFilter (the files are ~2GB) and still be able to the logic to check SF before and after the current SF?

**Comment by YogeshSharma1985** [comment]
Actually ignore my previous comment, I have made some progress since then. 
Now I just need to see how can I add or delete a structured field (BNG/ENG/EDT) just above/below the current SF when using AFPFilter (I am dealing with large AFP files).
 case SFName.NOP_VALUE:
				    	NOP nop = (NOP) sf;
				    	String S5 = new String(nop.getUndfData(), "Cp1047") 
\\This is to convert undf EBCDIC byte array from NOP
				    	if(S5.contains("FILE_SHEET_COUNT")) {
				    		EDT edt = AfplibFactory.eINSTANCE.createEDT();
							edt.setDocName("DOC00001");
							out.writeStructuredField(edt);
							return STATE.UNTOUCHED;
				    	}
				    	return STATE.UNTOUCHED;

**Comment by yan74** [comment]
Well, using out.writeStructuredField should work - however something tells me this is not going to work with Buffered(In/Out)putStream. Not quite sure why, but I think the buffer will garble the output. Again, just a feeling. Adding before the current SF should be like you did above. For adding after the current if would write the current SF, write your new SF and then return DROP.

**Comment by yan74** [comment]
I found why I was suspicious about Buffered(In/Out)putStream - had nothing to do with your use case. [https://github.com/yan74/afplib/wiki/Reading-AFP](https://github.com/yan74/afplib/wiki/Reading-AFP)

**Comment by YogeshSharma1985** [comment]
That worked great, Thanks.
I am still trying to figure out if I can read the next or prior SF while I am looping through a current SF.
Let me know if you have any suggestions. 
Wondering If I can use the index (getNumber function) by decrementing it by 1 and then be able to get the SF value prior using some function.

**Comment by yan74** [comment]
What I did in the past if I needed to read ahead is collecting all SF in a buffer (e.g. LinkedList) until I am sure that I can write them to disk. Then I write all SF from the buffer and clear the buffer. Then again read ahead while collecting again until I get to the end of the file. Usually you can keep the buffer quite small (e.g. collect all SF for a page). But this would not make use of AfpFilter but just using an AfpInputStream and AfpOutputStream and reading until the input stream returns null (end of file).

**Comment by YogeshSharma1985** [comment]
Yan,

    Thanks for responding, that worked great.

   I ended up dropping all BNG/ENG tags and recreating them based on logic you gave to add new field either either below or above a NOP.



Regards,
Yogesh
