### ISSUE TITLE
Not an Issue : How To Create AFP file with Images

### ISSUE THREAD

**Issue by harimurra** [yan74/afplib#5]
Hi Yan,

Is there a reference to create a sample AFP file with Images ?

**Comment by yan74** [comment]
Hi @harimurra,

currently there is none, but I can add some snippet on how to do this. Would that be object container or IOCA images?

**Comment by harimurra** [comment]
Hi Yan, Thanks a lot for response, it is Object container.

**Comment by yan74** [comment]
Hi @harimurra,

so I added following sample: 

https://github.com/yan74/afplib/blob/master/org.afplib.samples/src/main/java/org/afplib/samples/snippets/IncludeImage.java 

that includes a tiff as object container into the resource group and references that image from a page. The code contains a main method taking the name of the afp to create and the tiff to read.

**Comment by yan74** [comment]
This is how it looks like in an AFP viewer:

![test](https://cloud.githubusercontent.com/assets/7473685/25872676/e5ab2a52-350b-11e7-80df-2e8882923bfd.png)

**Comment by harimurra** [comment]
Yan, 
Thank you. **Thanks for amazing library.**
