### ISSUE TITLE
tripletId=0 for all Triplets read through AfpInputStream

### ISSUE THREAD

**Issue by moritzfl** [yan74/afplib#53]
I am using afpLib to parse AFP-Files into structured fields and then read their contents and attributes. In essence, this similar to what the DumpAFP example does (org.afplib.samples/src/main/java/org/afplib/samples/DumpAFP.java).
However, when reading afp-files that way, the tripletIds do not seem to be persisted anywhere in a parsed object. If for example I come across an Instance of MediaEjectControlImpl, the tripletId is 0 while it should be 69.
Am I missing something here or is this a bug?

**Comment by yan74** [comment]
Hi Moritz,

nice catch - thanks! Indeed this is a bug. I fixed it in latest commit (19269252a33edcb66740ffdb211f8043e958adc2)

**Comment by moritzfl** [comment]
Thanks for the quick response and fix. Truly awesome 👍. Do you plan on publishing a release soon by any chance?

**Comment by yan74** [comment]
released v0.0.15 - search.maven.org should have it soon
