### ISSUE TITLE
Class cast exception

### ISSUE THREAD

**Issue by krishnansanjeev** [yan74/afplib#55]
Hi,
I have a requirement to combine multiple AFP files, i tried running the AFPCombine, i could see the resources renamed and the exception occurs when it writes the resources of the first file, 

java.lang.ClassCastException:
org.afplib.afplib.impl.BRSImpl cannot be cast to org.afplib.afplib.ERS
at AfpCombine.writeResourceGroup(AfpCombine.java:501)

I tried to access it as a SF but it throws a 5a Magic byte not found error

I am a beginner  to AFP file processing, any help would be much appreciated.

**Comment by yan74** [comment]
Hi @krishnansanjeev 

can you run it with `-Dlog4j.configuration=debug.properties` and paste the output? - Also could you include the full stack trace of the error?

**Comment by krishnansanjeev** [comment]
Apologies, 

I work in a restricted environment. I couldn’t share those. 


Thank you !

**Comment by yan74** [comment]
Then I am not quite sure how to help :)
