### ISSUE TITLE
Not Issue: Do you have any samples which draws lines/tables in AFP files?

### ISSUE THREAD

**Issue by bintesh** [yan74/afplib#6]

**Comment by yan74** [comment]
@bintesh,

this could either be achieved in GOCA or PTOCA. But that would be rather large piece of code since there would be lot of GOCA commands or PTOCA chained sequences involved. It would also not be very readable. If you want to do document composition you may want to look for Apache FOP. AFPlib's purpose is to have a low level API on manipulating structured fields not build pages or content from scratch (although: could be done - just being very cumbersome). Having said this you could build a higher level API on top of AFPlib that helps you draw lines ...

**Comment by bintesh** [comment]
Thanks yan

**Comment by harimurra** [comment]
It May Help 

`PTX ptx = new AfpBuilder()
			.withMember(new AfpBuilder()								// Text Orientation -> Left to Right // Top to Bottom
					.with(AfplibPackage.STO__IORNTION, STOIORNTION.CONST0DEGREES_VALUE)
					.with(AfplibPackage.STO__BORNTION, STOBORNTION.CONST90DEGREES_VALUE)
					.create(STO.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.AMB__DSPLCMNT, 1422)			
					.create(AMB.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.AMI__DSPLCMNT, 2262)				
					.create(AMI.class))
			.withMember(new AfpBuilder()								
					.with(AfplibPackage.STC__FRGCOLOR, STCFRGCOLOR.CONST_RED_VALUE)
					.create(STC.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.SCFL__LID, 1)					// identifier mapped in MCF above
					.create(SCFL.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.TRN__TRNDATA, text)
					.create(TRN.class))
			.withMember(new AfpBuilder()								
					.with(AfplibPackage.STC__FRGCOLOR, STCFRGCOLOR.CONST_RED2_VALUE)
					.create(STC.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 255)
					.create(SEC.class))
			
			.withMember(new AfpBuilder()								
					.with(AfplibPackage.STC__FRGCOLOR, STCFRGCOLOR.CONST_BLACK_VALUE)
					.create(STC.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 255)
					.create(SEC.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.AMB__DSPLCMNT, 1452)			
					.create(AMB.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.AMI__DSPLCMNT, 2262)				
					.create(AMI.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.DIR__RLENGTH, 2500)	
					.with(AfplibPackage.DIR__RWIDTH, 15)	
					.create(DIR.class))
			.withMember(new AfpBuilder()								
					.with(AfplibPackage.STC__FRGCOLOR, STCFRGCOLOR.CONST_RED_VALUE)
					.create(STC.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 0)
					.with(AfplibPackage.SEC__COLSIZE1, 255)
					.create(SEC.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.AMB__DSPLCMNT, 1722)			
					.create(AMB.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.AMI__DSPLCMNT, 2262)				
					.create(AMI.class))
			.withMember(new AfpBuilder()
					.with(AfplibPackage.DBR__RLENGTH, 150)
					.with(AfplibPackage.DBR__RWIDTH, 550)
					.create(DBR.class))
			.create(PTX.class);`
