### ISSUE TITLE
Error displaying PDF converted to AFP.

### ISSUE THREAD

**Issue by JesusGarciaMinas** [yan74/afplib#61]
Hello,

I am creating a converter from PDF files to AFP files. To do this, I have used examples that you have in the code and I have reviewed other issues that have asked you related questions.

However, I have a problem. Once I generate the AFP file, depending on the viewer I use, I get different results. If I use your viewer or papyrus software, they return the file correctly but others such the IBM Internter Explorer plugin returns a red background document or in the case of the printer software to be used to print the documents it gives an error.

I have been researching and I think it is related to the code "T1000395" as it is the error message displayed when parsing and validating the AFP document. I have tried to modify it and use other types of fonts based on an original document that they have given me and that they use to print, but it still gives the same error in those programs.

I appreciate your help and if you need more information I will explain you without problems.

Thank you.

**Comment by yan74** [comment]
Hi Jesus,

If you are just encapsulating PDF in AFP then you wouldn't need the code page T1000395 nor the font C1N20000 - you can just remove it (so basically the whole MCF and BPT, PTX and EPT), but most likely your problem is related to PDF object container. Older viewers like the IBM Internet Explorer plugin are not able to render PDF object container. Also some printers, esp. black and white printers are not able to print pdf object container. Most modern color (production) printer however have no problem with these files.

**Comment by JesusGarciaMinas** [comment]
Hi Yan,

I give you a little more information about the problem we have with the AFP file. I have generated a new file removing both the encoding and the source as you said in your answer to my post. However, the printer software gives an error that an ENG structure was expected instead of the end-of-document EDT structure. To give you more feedback and see if you can help me, I am attaching the image with the error provided by the printer and an AFP file generated with the same program (the file itself is not the same since for confidentiality reasons I cannot provide it).
![printer](https://user-images.githubusercontent.com/36407854/149386945-bc9a8acd-5617-4479-8695-c0335fbcc1f8.jpg)

Thanks,
Greetings
[Attached files.zip](https://github.com/yan74/afplib/files/7865102/Attached.files.zip)
.

**Comment by JesusGarciaMinas** [comment]
Hello,

After carrying out the steps that you indicated in the previous one, the printing process of the AFP file has worked correctly. 

Thank you.
