### ISSUE TITLE
State of the Project

### ISSUE THREAD

**Issue by moritzfl** [yan74/afplib#67]
It has been quite a while since the last time changes were made to this project which leaves me wondering if the author (@yan74) still considers this project to be in active development or continuing development in a fork may make more sense.

So this issue is basically an inquiry about the state of the project. It would be nice if @yan74 could clear things up.

**Comment by yan74** [comment]
It is active - just too much on my plate right now - If you want me to look at anything specific with priority ... like your pull request I can do

**Comment by moritzfl** [comment]
thanks for your response!

We have no pressing issues as we do have workarounds in place. Thanks for the offer of prioritizing topics of interest though.

I was just a little uncertain about future development in this project which might have resulted in us picking another route for the solutions that we currently have in place (i.e. maintaining a fork of afplib or extending our existing AFP related implementation with the functions we currently rely on from afplib).
