### ISSUE TITLE
Get Page and Barcode(s)? (not an issue)

### ISSUE THREAD

**Issue by coloboxp** [yan74/afplib#7]
Hi yan74,

I know this is not an issue, but I wanted to ask you, how would be possible to get the "current page" and a list of barcodes?

I'm using your lib and I've been experimenting with it, I've started with the sample `DumpAFP.java` but it's obvious that my knowledge of AFP or your lib's API is far from good.

In a windows app I've found, I managed to find out that the barcodes are allocated on fields "`PTX`", they are DataMatrix ones.

Would you mind to drop me some hints?

Thank you so much in advance,

Alejandro

**Comment by yan74** [comment]
Hi @coloboxp,

finding DataMatrices on a pages could be done with afplib, if you know which font they are encoded in. Reading the content of it is a different story. This highly depends on if you are able to "decode" from the codepoints that build a DataMatrix on a page. I was trying to find an example of DataMatrix as PTX, but I could only find a linear barcode - however the principle would be the same:

![2of5](https://cloud.githubusercontent.com/assets/7473685/25800387/694514c8-33e9-11e7-8711-0d9c8fb37f3b.png)

This shows a TRN with codepoints 0xc2 0x2d 0x78 0xdf .... these are used to find the appropriate glyps in the font (C0AAABT0):

![font](https://cloud.githubusercontent.com/assets/7473685/25800603/4fe52918-33ea-11e7-817f-2ee9c3391f12.png)

So again all depends on if you could work with those codepoints (0xc2 0x2d ...) or not.

**Comment by coloboxp** [comment]
Thank you very much for sharing your knowledge and giving me some ideas!, I'll look into it.

cheers
